
apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::160885265516:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-SbfgbYSSoQvc
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::614388036472:user/suresh
      username: suresh

kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system|
    resourceVersion: "1030"
    uid: 9b1c8e5a-0c3d-4f1b-9c8e-2b1a2c3d4e5f